export const AppConstants = {
    SET_APP_LOADED: 'SET_IS_APP_LOADED',
    SET_IS_PROCESS: 'SET_IS_PROCESSING'
};

export const AuthConstants = {
    AUTHENTICATE_USER_REQUEST: 'AUTHENTICATE_USER_REQUEST',
    AUTHENTICATE_USER_RESPONSE_SUCCESS: 'AUTHENTICATE_USER_RESPONSE_SUCCESS',
    AUTHENTICATE_USER_RESPONSE_FAILURE: 'AUTHENTICATE_USER_RESPONSE_FAILURE',
  
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_RESPONSE_SUCCESS: 'LOGIN_RESPONSE_SUCCESS',
    LOGIN_RESPONSE_ERROR: 'LOGIN_RESPONSE_ERROR',
  
    LOGOUT: 'LOGOUT'
};

export const UserConstants = {
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_RESPONSE_SUCCESS: 'GET_USER_RESPONSE_SUCCESS',
    GET_USER_RESPONSE_ERROR: 'GET_USER_RESPONSE_ERROR'
};

export const ProductMetadataConstants = {
    UPDATE_METADATA: 'UPDATE_METADATA',
    CLEAR_METADATA: 'CLEAR_METADATA',
    SET_QRCODE_PROCESSING: 'SET_QRCODE_PROCESSING'
};

export const ProductBlockchainConstants = {
    GET_MULTI_CHAIN_REQUEST: 'GET_MULTI_CHAIN_REQUEST',
    GET_MULTI_CHAIN_RESPONSE_SUCCESS: 'GET_MULTI_CHAIN_RESPONSE_SUCCESS',
    GET_MULTI_CHAIN_RESPONSE_ERROR: 'GET_MULTI_CHAIN_RESPONSE_ERROR',
    GET_FACTOM_ENTRY_REQUEST: 'GET_FACTOM_ENTRY_REQUEST',
    GET_FACTOM_ENTRY_RESPONSE_SUCCESS: 'GET_FACTOM_ENTRY_RESPONSE_SUCCESS',
    GET_FACTOM_ENTRY_RESPONSE_ERROR: 'GET_FACTOM_ENTRY_RESPONSE_ERROR'
};