export const appConstants = {
    SET_APP_LOADED: 'SET_IS_APP_LOADED',
    SET_IS_PROCESS: 'SET_IS_PROCESSING',
    SET_QRCODE_PROCESSING: 'SET_QRCODE_PROCESSING'
};

export const authConstants = {
    AUTHENTICATE_USER_REQUEST: 'AUTHENTICATE_USER_REQUEST',
    AUTHENTICATE_USER_RESPONSE_SUCCESS: 'AUTHENTICATE_USER_RESPONSE_SUCCESS',
    AUTHENTICATE_USER_RESPONSE_FAILURE: 'AUTHENTICATE_USER_RESPONSE_FAILURE',
  
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_RESPONSE_SUCCESS: 'LOGIN_RESPONSE_SUCCESS',
    LOGIN_RESPONSE_ERROR: 'LOGIN_RESPONSE_ERROR',
  
    LOGOUT: 'LOGOUT'
};

export const userConstants = {
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_RESPONSE_SUCCESS: 'GET_USER_RESPONSE_SUCCESS',
    GET_USER_RESPONSE_ERROR: 'GET_USER_RESPONSE_ERROR'
};

export const productMetadataConstants = {
    UPDATE_METADATA: 'UPDATE_METADATA'
};